export const data = [
  {
    title: "Security",
    para:
      "We have implemented appropriate technical and security measures to safeguard your information from unauthorized or unlawful access, accidental loss, destruction, or damage. When collecting data through the Site, we ensure that your personal details are collected on a secure server. Our servers are equipped with firewalls for added protection. For electronic collection of payment card details, we employ encryption using Secure Socket Layer (SSL) coding. Although we cannot provide a guarantee of 100% security, these measures make it difficult for hackers to decrypt your information. We strongly advise against sending full credit or debit card details in unencrypted electronic communications with us. We maintain physical, electronic, and procedural safeguards to protect your information during its collection and disclosure. As part of our security protocols, we may occasionally request proof of identity before disclosing personal information to you. It is your responsibility to safeguard your password and computer against unauthorized access.",
  },
  {
    title: "Log Information",
    para:
      "Whenever you visit Domus Flowers, certain information is transmitted from your browser to our server log files and is subsequently stored. This information includes the date and time of your visit, the pages you accessed, your IP address, the URL of the site that referred you to Domus Flowers, the amount of information stored, and the browser you utilized. Upon gathering this data, all IP addresses are either deleted or anonymized. Anonymization involves altering your IP address in a way that prevents it from being linked to the original user, or making such a connection possible only through extensive research. The anonymous information stored in our log files is then utilized to enhance the shopping experience on the Domus Flowers website. This includes improving navigation, promptly identifying errors, and allocating server resources effectively. For instance, this information helps us identify peak usage periods and allocate sufficient server power to ensure optimal site performance during those times. By providing my consent, I authorize Domus Flowers to analyze and utilize protocol data for the purpose of developing and optimizing their online shop.",
  },
  {
    title: "Cookies",
    para:
      "While visiting our website, it is not mandatory to accept cookies. However, if you wish to place an order or add items to your shopping basket, it is necessary to configure your browser settings to accept cookies. This will enable you to utilize the shopping basket and checkout functions effectively.",
  },
  {
    title: "What are cookies?",
    para:
      "Cookies and flash cookies are small files that are stored on your device, such as your computer or mobile device. These files contain specific information related to your preferred settings and other data that our system requires to interact with your browser. There are two main types of cookies: Session cookies: These cookies are deleted as soon as you close your browser. They are temporary in nature and are used to facilitate your current browsing session. Temporary/Permanent cookies: These cookies are stored on your device for a longer duration or, in some cases, permanently. They help us customize our website to suit your preferences and reflect your browsing habits. Additionally, they allow us to remember information you have previously entered, eliminating the need for you to re-enter it on your next visit. Cookies play a crucial role in enhancing your browsing experience by personalizing the website content based on your interests and ensuring a smoother interaction with our site.",
  },
  {
    title: "What kind of cookies does DomusFlowers.com use?",
    para:
      "Domus Flowers primarily uses session cookies, which are automatically deleted at the end of your browser session. These cookies enable you to utilize features like our shopping basket across multiple pages of our website. We also employ a few cookies that remain on your computer even after you close your browser. These cookies serve the purpose of recognizing your previous visits to our website and remembering your preferred settings and products. These temporary/permanent cookies have a lifespan ranging from one month to two years, after which they are automatically deleted. The data collected through these cookies allows us to analyze and gather insights to improve our website. This helps us enhance the user experience, making it more convenient and tailored to your preferences. Additionally, it enables us to provide personalized product recommendations that align with your interests. Our goal is to offer you an enjoyable and effortless shopping experience on a website that caters to your individual tastes.",
  },
  {
    title: "Re-targeting",
    para:
      "Domus Flowers employs retargeting technology to enhance the relevance of our online offerings for you. This technology enables us to display advertisements for recently viewed and related products on our partner websites. As a result, our ads, even on other companies sites, are tailored to align with your interests and preferences. This is achieved by analyzing user behavior using data collected by our cookies. It's important to note that this information is completely anonymous and does not involve storing any personal data or creating user profiles. Our focus is on understanding and responding to user behavior patterns to deliver more engaging and personalized advertising experiences without compromising your privacy.",
  },
  {
    title: "How can I prevent cookies from being stored on my computer?",
    para:
      "To prevent cookies from being stored on your computer, you can adjust the settings in your browser. Here are general steps to manage cookies: In your browser, access the settings or preferences menu. Look for the section related to privacy or cookies. You may have options to block all cookies, accept cookies only from certain websites, or prompt for permission before accepting cookies. If you wish to accept cookies from Domus Flowers but block third-party cookies, look for an option to block or manage third-party cookies specifically. Consult your browser's help section or documentation for more specific instructions on managing cookie settings. It's worth noting that if you choose to block cookies, it may impact the functionality and user experience of certain websites.",
  },
  {
    title: "Data Collected",
    para:
      "When you place an order for a product on the Domus Flowers website, we may collect and process various information to fulfill your purchase and provide our services to you. The data we may collect includes your title, name, gender, email address, postal address, delivery address (if different), telephone number, mobile number, fax number, payment details, payment card details, or bank account details. We will use the information you provide to process your orders, deliver the requested services and information, administer your account, verify and process financial transactions, analyze website usage, improve our website, customize content for users, conduct demographic research, and send you relevant information about our products and services, unless you have indicated that you do not wish to receive such communications. You can opt out of marketing communications at any time. In order to facilitate the delivery of your product, we may share your name and address with third-party courier services or suppliers. We may also use your phone number to notify you about the status of your order and inform you about the latest deals and campaigns. Payments made through the website will be processed by our agent, and it's important that you provide accurate and up-to-date information. Your order details are stored with us for security purposes, but we are unable to directly retrieve them. However, you can access this information by logging into your account on the website. From there, you can view completed, open, and upcoming orders, manage your address and bank details, and update your newsletter subscription. It is your responsibility to keep your personal access data confidential and not share it with unauthorized third parties. We are not liable for any misuse of passwords unless it is due to our negligence.",
  },
  {
    title: "Credit Check and Fraud Prevention",
    para:
      "In order to assess the validity of orders placed on the Domus Flowers website, we may collaborate with fraud prevention agencies (FPAs). These agencies assist us in making informed decisions regarding the acceptance of orders. Here is a summary of how we and the FPAs may use your information: We will conduct searches with FPAs to obtain relevant information about individuals placing orders on the website. The information provided by FPAs will be utilized to aid us in making decisions regarding all individuals placing orders on the website. If it is discovered that false or inaccurate information has been provided to us, and we identify fraudulent activity, the relevant details may be shared with FPAs. If you would like more detailed information about this process or the specific agencies we work with, please feel free to contact us. Please be aware that providing false or inaccurate information may result in the disclosure of such information to FPAs if fraud is detected.",
  },
  {
    title: "Other uses of your personal information",
    para:
      "We may utilize your personal information for opinion and market research purposes. Rest assured that your details will remain anonymous and will only be used for statistical analysis. You have the option to opt out of this research at any time. Any responses you provide in surveys or opinion polls conducted by Domus Flowers will not be shared with third parties. Your email address will only be required if you wish to participate in competitions, and we store survey answers separately from email addresses. Additionally, we may send you information about Domus Flowers, the Site, our other websites, our products, sales promotions, newsletters, and relevant updates from our group companies or business partners. If you prefer not to receive any of this additional information, you can unsubscribe by clicking the designated link in any email sent to you. Upon receiving your instruction, we will cease sending you the requested information within 7 working days. If your instruction is unclear, we may contact you for clarification. We may also anonymize data related to Site users for various purposes, such as determining the general location of users and analyzing the usage of specific aspects of the Site or links included in emails sent to registered users. This anonymized data may be shared with third parties, such as publishers. However, this anonymized data will not be capable of personally identifying you.",
  },
  {
    title: "Competitions",
    para:
      "For any competition we use the data to notify winners and advertise our offers. You can find more details where applicable in our participation terms for the respective competition.",
  },
  {
    title: "Third parties and links",
    para:
      "We may share collected personally identifying information (including email addresses) with other companies in our group and for commercial purposes - such as advertising. We may also pass your details to our agents and subcontractors to help us with any of our uses of your data set out in our Privacy Policy. For example, we may use third parties to assist us with delivering products to you, to help us to collect payments from you, to analyse data and to provide us with marketing or customer service assistance. We may exchange information with third parties for the purposes of fraud protection and credit risk reduction. We may transfer our databases containing your personal information if we sell our business or part of it. Other than as set out in this Privacy Policy, we shall NOT sell or disclose your personal data to third parties without obtaining your prior consent unless this is necessary for the purposes set out in this Privacy Policy or unless we are required to do so by law. The Site may contain advertising of third parties and links to other sites or frames of other sites. Please be aware that we are not responsible for the privacy practices or content of those third parties or other sites, nor for any third party to whom we transfer your data in accordance with our Privacy Policy.",
  },
];
